version: 2

project_name: lore

before:
  hooks:
    - go mod tidy

builds:
  - binary: lore
    ldflags:
      - -X main.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows

archives:
  - format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

release:
  github:
    owner: robinovitch61
    name: lore

brews:
  - name: lore
    homepage: https://github.com/robinovitch61/lore
    description: "A terminal pager with search, filter, and selection."
    directory: Formula
    commit_author:
      name: "Leo Robinovitch"
      email: "leorobinovitch@gmail.com"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: robinovitch61
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

aurs:
  - name: "lore-bin"
    homepage: "https://github.com/robinovitch61/lore"
    description: "A terminal pager with search, filter, and selection."
    maintainers:
      - "Leo Robinovitch <leorobinovitch@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/lore-bin.git"
    depends:
      - "glibc"
    commit_author:
      name: "Leo Robinovitch"
      email: "leorobinovitch@gmail.com"
    skip_upload: auto

nix:
  - name: lore
    commit_author:
      name: "Leo Robinovitch"
      email: "leorobinovitch@gmail.com"
    homepage: "https://github.com/robinovitch61/lore"
    description: "A terminal pager with search, filter, and selection."
    license: "mit"  # must be lowercase
    skip_upload: auto
    repository:
      owner: robinovitch61
      name: nur-packages
      branch: main
      token: "{{ .Env.NUR_PACKAGES_GITHUB_TOKEN }}"

winget:
  - name: lore
    publisher: robinovitch61
    license: MIT
    copyright: "Leo Robinovitch"
    homepage: https://github.com/robinovitch61/lore
    short_description: "A terminal pager with search, filter, and selection."
    package_identifier: "robinovitch61.lore"
    repository:
      owner: "robinovitch61"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

scoops:
  - repository:
      owner: "robinovitch61"
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@theleo.zone
    homepage: https://github.com/robinovitch61/lore
    description: "A terminal pager with search, filter, and selection."
    license: MIT
gomod:
  proxy: true
